#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)

groups:
    default:
    authentication:
        global_basic_auth:
            user: leonardo.suporte@brgaapempresarial.com.br
            password: u3r5v8k9cwporw